### ISSUE TITLE
Please clarify documentation

### ISSUE THREAD

**Issue by Whistler7** [Maratyszcza/PeachPy#1]
I have a 4th-generation Intel Haswell CPU on Windows.  I want to use PeachPy to speed up the inner loops of my code written in Python.

After reading several papers on PeachPy, I haven't been able to understand whether execution of PeachPy-generated assembly code in Python is:
a) full-speed using native CPU instructions
b) emulated

a) implies that PeachPy could offer higher execution speed than Cython, without a separate assembler.
b) implies that PeachPy could be used to cross-develop and functional test for all supported architectures on one machine, but a separate assembler step is needed for each platform and OS.

Both of these are good goals.  Which one describes PeachPy?

**Comment by Maratyszcza** [comment]
PeachPy generates native CPU instructions. On Mac & Linux you can do

```python
from peachpy import *
from peachpy.x86_64 import *

x = Argument(int32_t)
y = Argument(int32_t)
with Function("DotProduct", (x, y), int32_t) as asm_function:
    reg_x = GeneralPurposeRegister32()
    reg_y = GeneralPurposeRegister32()

    LOAD.ARGUMENT(reg_x, x)
    LOAD.ARGUMENT(reg_y, y)
    ADD(reg_x, reg_y)
    MOV(eax, reg_x)
    RETURN()

# abi.microsoft_x64_abi for Windows
py_function = asm_function.finalize(abi.system_v_x86_64_abi).encode().load()

print(py_function(2, 2)) # -> 4
```

However, in your case there are two catches:
1. The [bytecode loader](https://github.com/Maratyszcza/PeachPy/blob/master/peachpy/loader.py) is currently not implemented on Windows
2. PeachPy currently does not implement prologue/epilogue sequences, so if your function uses non-volatile registers, something bad will happen.

**Comment by Whistler7** [comment]
Thanks for the clarification and example.  Do the same two catches exist with your older code that only supports Python 2 (https://bitbucket.org/MDukhan/peachpy/)?

Does catch number 2 also exist with Mac & Linux?

Could you create issues for catches 1 and 2?

I will periodically check back to see when they are resolved so I know when I can use PeachPy with 64-bit Windows.

**Comment by Maratyszcza** [comment]
This version (PeachPy 0.2.x) is a near-complete rewrite of the old PeachPy (PeachPy 0.1.x). PeachPy 0.1.x did generate prologue/epilogue sequences, but it relied on external assembler (nasm or GNU assembler) to convert instructions into opcodes. Thus is doesn't suit you use-case.

**Comment by Maratyszcza** [comment]
Please follow #3 and #5
