### ISSUE TITLE
Go-amd64: Code generated for three-operand IMUL is invalid

### ISSUE THREAD

**Issue by robskie** [Maratyszcza/PeachPy#21]
Hi again!

I tried generating code for `IMUL(rax, rbx, 10)` which outputs `IMULQ BX, $10, AX` which is not recognized by Go. Removing BX from the instruction, `IMULQ $10, AX`, makes it valid.

**Comment by Maratyszcza** [comment]
Fixed with dc4ec1b0856a77a0f08b6d2d0244ee987d14e8ba. You'd need to upgrade `opcodes` and re-generate PeachPy:
```
cd PeachPy
git pull
pip install --upgrade -r requirements.txt
python setup.py generate
pip install --upgrade .
```
