### ISSUE TITLE
Go-amd64: How to specify a memory operand as m8/m16/m32/m64?

### ISSUE THREAD

**Issue by robskie** [Maratyszcza/PeachPy#23]
For example, CRC32 has the following supported forms:

            * CRC32(r32, r8/m8)
            * CRC32(r32, r16/m16)
            * CRC32(r32, r32/m32)
            * CRC32(r64, r8/m8)
            * CRC32(r64, r64/m64)

Given an r64 as the first operand, how can I tell the code generator that the second operand is an m64 and not an m8? Trying `CRC32(rax, [rbx])` generates `CRC32B 0(BX), AX` which assumes that [rbx] is m8. How could I make the generated code to be `CRC32Q 0(BX), AX` instead?

**Comment by Maratyszcza** [comment]
Did you try `qword[rbx]`?

**Comment by robskie** [comment]
It works! Thanks!
