### ISSUE TITLE
Go-amd64: How to declare constants?

### ISSUE THREAD

**Issue by robskie** [Maratyszcza/PeachPy#24]
I'm trying to move a constant value to an xmm register through these instructions:
```
    mask = Constant.uint64x2(0xFF, 0xFF, 'mask')
    MOVDQU(xmm0, mask)
```
which produces this instruction:
```
    MOVOU const0xFF00000000000000FF00000000000000(SB), X0
```
This will output `const0xFF00000000000000FF00000000000000: not defined` in Go. How can I generate code like this instead?
```
    DATA     mask<>+0(SB)/8, $0xFF
    DATA     mask<>+8(SB)/8, $0xFF
    GLOBL    mask<>(SB), 8, $16
    ...
    ...
    ...
    MOVOU mask<>(SB), X0
```

**Comment by Maratyszcza** [comment]
Constant support is a work-in-progress. Currently they are implemented on all platforms, but Golang. Please follow #11
