### ISSUE TITLE
How do we debug C/C++ Application

### ISSUE THREAD

**Issue by kvaragan** [Maratyszcza/PeachPy#35]
I have a question:
Say I am developing an application in C/C++ and part of the code I develop in assembly, If I use peachpy to write this assembly code, How am I going to debug this assembly code?

In visual studio while using yasm assebler this was possible. Is similar kind of thing can be done in PeachPy?

How PeachPy is different from using intrinsics? 
ThankYou

**Comment by Maratyszcza** [comment]
I debug PeachPy code by organizing it into small Python functions, which generate small snippets of assembly, and writing unit tests for them (you can write unit tests for PeachPy assembly in Python, BTW).

PeachPy currently does not generate debug information, so source-level debugging is not supported.

PeachPy is closer to assembly, than to C intrinsics. In particular:

- It uses assembly-like syntax
- It does not spill registers (register allocation failure would result in an error, not register spills)
- It does not reorder instructions
- It works for platforms where support for intrinsics is poor (Native Client) or non-existent (Golang)

**Comment by kvaragan** [comment]
Thank You,
Do we have an option to select what registers to be used, like some assembler's allow.

**Comment by Maratyszcza** [comment]
You can use conventional register names, i.e. `MOVAPS(xmm0, [rsi + 64])` is perfectly valid.

You can mix physical registers and virtual registers (e.g. created with `XMMRegister()`) in the same code. PeachPy does liveness analysis to ensure that it doesn't reuse the same hardware register for different variables.

**Comment by kvaragan** [comment]
Thats very nice, do you have performance comparison between peachPy generated assembly vs direct assembly coding.

**Comment by Maratyszcza** [comment]
PeachPy **is** direct assembly coding, but with nicer syntax

**Comment by kvaragan** [comment]
Thank You

**Comment by kvaragan** [comment]
Hi,
Where do I get full documentation for the PeachPy, most important assembly syntax so I can write some assembly code.

Thank You,
Kiran V

**Comment by Maratyszcza** [comment]
There is currently no documentation for PeachPy, but the syntax mimicks Intel assembly in NASM/FASM flavour. The few extra pseudo-instructions are:

- `LOAD.ARGUMENT reg, arg`
- `RETURN [imm/reg]`
- `LABEL label`

**Comment by kvaragan** [comment]
Hi,
How do I learn this PeachPy, start with NASM assembler ?
Regards,
Kiran V

**Comment by kvaragan** [comment]
Hi,
How do I compile for x86 rather than x64 when I generate obj files from python PeachPy files ?
Regards,
Kiran

**Comment by Maratyszcza** [comment]
I expect that PeachPy users are already familiar with x86-64 instructions, but if not, you'll find descriptions in ISA manuals from Intel and AMD.

As for x86 (32-bit) assembly, the current version of PeachPy does not support it.

**Comment by kvaragan** [comment]
Thank You,
I was trying to evaluate assemblers and one of the key issues was portability then I came across PeachPy. I find peachPy useful but any plans to support source-level debugging & 32-bit in near future?
Regards,
Kiran

**Comment by Maratyszcza** [comment]
What is the nature of the project? You can email me privately (see my email in GitHub profile) if you don't want to discuss it publicly.
