### ISSUE TITLE
Do examples run on Win / Python 3.5?

### ISSUE THREAD

**Issue by cforger** [Maratyszcza/PeachPy#36]
Hi,

 Looks like an awesome project, but I'm not able to get started.

 My env is Win64 with Python3.5

 If I take the example on the main page, under "Using PeachPy as a command-line tool" and then I execute the specified line 

"python -m peachpy.x86_64 -mabi=ms -mimage-format=ms-coff -o example.obj example.py"

I get errors.:

  File "C:\Users\xxx\AppData\Local\Programs\Python\Python35-32\lib\site-packages\peachpy\encoder.py", line 151, in fixed_string
    assert isinstance(size, (int, long)) and size > 0, "size %u is not a positive integer" % size
NameError: name 'long' is not defined

I'm finding similar issues for the other examples. I've taken a look, but before I invest any time in seeing if my env is missing something, I thought I should check that I'm even expect to be able to output anything meaningful on my platform.

I'd also love any 'in progress but not ready' documentation you may have on this latest version. There's very little out there, and online examples I see are for the old version. 

I've been fiddling with FASMg for a bit now, and this looks like a similar but better idea, and I get to stay in Python, so I'm quite eager to try it out.

**Comment by cforger** [comment]
Great, I'll pull and check in a sec. 

I'm finding more, do you want me to break them out as issues, or make one larger one?

**Comment by Maratyszcza** [comment]
Feel free to create new issues if you spot bugs. Neither Windows nor Python 3 is particularly popular among current PeachPy users, so you'd definitely meet some untested cases.

**Comment by cforger** [comment]
Great. I'm stuck in a MS world for my dev day-job, so it's just easier to stay here. I'll clean up what I encounter and post.
