### ISSUE TITLE
32 bit Python 3.5 in a 64 bit Windows 8.1 machine doesn't detect() abi correctly. 

### ISSUE THREAD

**Issue by cforger** [Maratyszcza/PeachPy#37]
Example:

x86_64\abi.py Line 134:

```
    elif osname == "Windows" and machine == "AMD64" and pointer_size == 8:
        return microsoft_x64_abi

```
But when I get here on my Windows 8.1 64 bit, running Python35 (32 bit Python35 BTW.. probably should install 64 bit) it skips this abi, because my pointer_size = 4, not 8.

..not sure if running a 32 bit Python on a 64 bit machine is even something you want to deal with. 

I didn't mean to install 32 bit Python, and will correct in a bit - let me know if you want me to flog PeachPy in this environment a bit more before I correct and I will.

**Comment by Maratyszcza** [comment]
What are you trying to do? Loading x86-64 assembly code as a Python function wouldn't work with 32-bit Python. If you just try to compile PeachPy code into an object file, you can explicitly specify `-mabi=ms`

**Comment by cforger** [comment]
I'm just exploring PeachPy at the moment.

My final goal (which I can do with FASMg but I rather with PeachPy) is outputing either an asm file to compile, or direct opcode obj of x86_64 AMD64 calling convention 

I'm installing the proper 64 bit Python and will try again with the latest revision, as 32 bit was not an intent.

**Comment by Maratyszcza** [comment]
`python -m peachpy.x86 -mimage-format=ms-coff -mabi=ms -o example.obj example.py` should work with 32-bit Python too. Let met know if it doesn't

**Comment by cforger** [comment]
Well, there isn't a x86 dir in the codebase under the peachpy dir, so it's not finding that.  You have arm, c, x86_64, etc.  I think that's the structure from the last version of PeachPy?

I think it may be easier to just say you need 64 bit Python to work with it. :)

**Comment by Maratyszcza** [comment]
Oops, should be `python -m peachpy.x86_64 ...`

**Comment by cforger** [comment]
Confirmed that it does output the example.obj in that condition, with 32 bit Python.

**Comment by cforger** [comment]
.. it's when I muck around a bit more and make a call directly to abi's detect() that I have issues. 

I've moved to 64 Bit Python, so it may not matter.

But, for clarification, Python32's struct.calsize("P") = 4 not 8, so that detect routine will miss.

**Comment by Maratyszcza** [comment]
96539c8b5b34f6532364f8f9d8d8147e0741ece8 should fix the situation when you don't specify `-mabi` on the command line. However, there is no way to make loading of x86_64 PeachPy functions work in 32-bit Python, because a 32-bit process can not run 64-bit code.

**Comment by cforger** [comment]
Great - I don't have a problem with that. 

How about a line to detect that attempt and warn/block?

**Comment by Maratyszcza** [comment]
It is detected here: on [line 1886 of peachpy.x86_64.function](https://github.com/Maratyszcza/PeachPy/blob/master/peachpy/x86_64/function.py#L1886)
