### ISSUE TITLE
-I problematic

### ISSUE THREAD

**Issue by kruus** [Maratyszcza/PeachPy#49]
Perhaps check for missing -I or somehow tell parser to initialize it to empty?

peachpy/x86_64/\_\_main\_\_.py
options.include is unset in many of your examples, so line 260:
`include_directories = [os.path.abspath(include_dir) for include_dir in options.include]`
fails with
   `TypeError: 'NoneType' object is not iterable`

Quickfix: add
`    include_directories = []`
`    if options.include is not None:`

**Comment by Maratyszcza** [comment]
Right, the "include" command-line argument needs a default value of an
empty list. Would you submit a PR?
