### ISSUE TITLE
the assembly_format - `gas` and `gnu`

### ISSUE THREAD

**Issue by ottolu** [Maratyszcza/PeachPy#51]
I try to use `PeachPy` to list the assembly of those `NNPACK` kernels in `gas` syntax form.
I simply add the flag "-S -assembly-format=gas" to `PeachPy` command in `ninja.build`, then run a normal build.
And the building process can't pass one line of assert: https://github.com/Maratyszcza/PeachPy/blob/master/peachpy/x86_64/pseudo.py#L63
Obviously, `gas` won't match the word `gnu`.

In the `abi_map`, I can't find the `gnu` format, so I guess the `gnu` tag might hold the same meaning as `gas`.
https://github.com/Maratyszcza/PeachPy/blob/master/peachpy/x86_64/__main__.py#L38

**Comment by Maratyszcza** [comment]
The mismatch is unintentional, `gas` and `gnu` are supposed to be the same thing. Generating assembly listing was properly implemented & tested only for Golang asm syntax, and if you get `gnu` syntax working, it would be a valuable contribution.

**Comment by Maratyszcza** [comment]
Should be fixed with 8375c3702e7ef342b959beef7e6946fdd273ee7b. `gas` is the supported value.
