### ISSUE TITLE
Where is the `syscall` instruction for X86_64?

### ISSUE THREAD

**Issue by ndouba** [Maratyszcza/PeachPy#52]

**Comment by Maratyszcza** [comment]
As PeachPy targets HPC audience, it doesn't include most system instructions. What is your use-case?

**Comment by pwaller** [comment]
My usecase is that I would like to write HPC code, and I would like to take accurate measurements with the PMU (performance monitoring unit). If I can minimise the amount of code between the target sequence and a `SYSCALL` to enable/disable monitoring (for example `prctl(PR_TASK_PERF_EVENTS_{DIS,EN}ABLE)` on linux), then the PMU measurement can become very accurate, since the amount of overhead will be minimal.

What is required to add `SYSCALL`?

**Comment by Maratyszcza** [comment]
Ok, I see. I'll add the `SYSCALL` instruction. The only modification is to describe it in `opcodes` package

**Comment by Maratyszcza** [comment]
You should be careful with this instruction though: PeachPy doesn't know which registers are produced and consumed, apart from `rcx` and `r11` (those are parts of ABI, no instruction specification).

**Comment by pwaller** [comment]
What is the best advice on that front? If you know which registers will be consumed, how do you prevent PeachPy from consuming them? My first thought is to push/pop the registers, but I assume this wouldn't actually help the liveness analysis. Also, what do you push/pop? If you were to push/pop the physical registers, I guess this would just mark them as live so they would be unused by the register allocator.

Would you consider having a way of annotating the instruction with information about what was consumed?

One idea that comes to mind:

```python
foo = SYSCALL()
foo.consumed = rax, rbx, rcx
```

or perhaps instead:

```python
SYSCALL(consumed=[rax, rbx, rcx])
```
The liveness analysis would then just consider those, too.

**Comment by Maratyszcza** [comment]
If your PeachPy function is just a stub that loads parameters and invokes the respective system call, I would expect it to just work. Do you plan to interleave `SYSCALL` with computational instructions?

**Comment by pwaller** [comment]
Yes, to try and totally avoid any overhead for measuring a sequence.

**Comment by Maratyszcza** [comment]
System calls are many time more expensive that subroutine calls anyways. I usually just measure and subtract the overhead inside the Linux kernel separately.

BTW, the first syntax is actually quite easy to implement, just define @property `consumed` in `Instruction` class and update `self._implicit_in_regs` accordingly.

**Comment by pwaller** [comment]
By "overhead", I mean overhead impact on the PMU measurement, not wall time. The PMU can be configured to exclude kernel time, so as soon as you hit the syscall instruction, it should stop counting.

**Comment by Maratyszcza** [comment]
Excluding kernel time through `perf_event` API is not perfect. BTW, did you see peachpy.io?

**Comment by pwaller** [comment]
I did, but I don't want to involve a third party in running/testing my code so I can't use that. I want my results to be reproducible for anyone with my code in the distant future. For instance, will peachpy.io continue to be up and available years from now? How does it work, by the way? Does it actually execute the code on a CPU of the specified type? The about text is quite short.

**Comment by pwaller** [comment]
> Excluding kernel time through perf_event API is not perfect

That may be so, but it looked quite good from a few preliminary tests I did (before this patch). I managed to reliably get counts which were only a few tens of cycles away from what I expected. I expect with the ability to do inline syscalls it may be even closer.

**Comment by Maratyszcza** [comment]
peachpy.io benchmarks on real CPUs, physically located at HPCGarage lab in Georgia Tech. It runs PeachPy inside a CPython interpreter inside the Web browser (either through PNaCl, or Asm.js), produces an ELF binary, and submits it to the server, which benchmarks it in a seccomp sandbox, and collects performance events through `perf_event` subsystem. The infrastructure is OSS, see https://github.com/PeachPy

**Comment by pwaller** [comment]
Very nice. That last point would be great to link to from the site! I couldn't find it :)

By the way, thanks for making all of this open source and accepting my contributions. It's a real pleasure to work with this stuff, even though it has a few rough edges.
