### ISSUE TITLE
Question about register allocation. 

### ISSUE THREAD

**Issue by blackball** [Maratyszcza/PeachPy#54]
Hi, 

I tried to print some information in Register._ _init_ _ to get some information of register allocation. Before it ran into the real codes, there're lots of register allocated.  Where do they allocated ? What for ? 

Thanks,

**Comment by Maratyszcza** [comment]
Physical register mnemonics are technically objects of Register subclass. See e.g. [peachpy/x86_64/registers.py#L276](https://github.com/Maratyszcza/PeachPy/blob/master/peachpy/x86_64/registers.py#L276)
