### ISSUE TITLE
Add Go support for MOVZX

### ISSUE THREAD

**Issue by dgryski** [Maratyszcza/PeachPy#58]
The `MOVZX` instruction is missing `go_name` entries meaning the instruction is emitted as a sequence of `BYTE` directives.

The Go assembler supports this instruction as `MOVBLZX`, `MOVBWZX`, `MOVBQZX`

**Comment by Maratyszcza** [comment]
Should be fixed with 05190c0da0a70479cfc85adbe9c10290a3f99f9a.
You'd have to reinstall dependencies and re-generate PeachPy instructions `pip install --upgrade -r requirements.txt && python setup.py generate`
