### ISSUE TITLE
Support for relative jumps in Go

### ISSUE THREAD

**Issue by pwaller** [Maratyszcza/PeachPy#68]
[Go's assembler allows you to write](https://golang.org/doc/asm), e.g:

```
JZ 2(PC)
```

Meaning, jump two instructions ahead. Would you consider supporting this, or not?

**Comment by dgryski** [comment]
Relative jumps are mostly useful for macros where you can't define a label.  You don't have that issue with peachpy because instead of a `#define` you'd write a python function and call that to generate your code.

Did you have a use for this or were you aiming for completeness?

**Comment by Maratyszcza** [comment]
@pwaller Unlikely, unless you have a good use-case that can't be solved with PeachPy's labels. PeachPy kind of supports this, but `JZ(rip+2)` means jump 2 **bytes** ahead.

**Comment by pwaller** [comment]
This is fair enough. My usecase was to write a highly unrolled loop that involved a sequence of JMPs. I wanted to avoid generating many labels. But I think the labels are not too bad, so I'll live with it for now.

By the way, I tried `JZ(rip+2)` but this didn't work. Is that a bug?

```
  File "example.py", line 203, in <module>
    JZ(rip+2)
NameError: name 'rip' is not defined
```

**Comment by Maratyszcza** [comment]
This feature is intended for testing rather than practical use, so `rip` is not imported into global namespace. Execute `from peachpy.x86_64.registers import rip` to use it.
