### ISSUE TITLE
rsp is not exposed through x86_64/__init__.py

### ISSUE THREAD

**Issue by eliben** [Maratyszcza/PeachPy#71]
I noticed that `x86_64/__init__.py` exposes registers from `registers.py` for easier access, but not `rsp`. Is there a specific reason for this, or just an oversight? I'll be happy to submit a fix PR if applicable

**Comment by Maratyszcza** [comment]
PeachPy manages stack frame itself: it would create prologue and epilog to save/restore clobbered non-volatile registers, allocate on-stack scratch space for local variables, and re-align the stack frame as needed. If a PeachPy program could manipulate stack frame via `rsp`, it would make PeachPy stack manipulation code a lot more compilated

**Comment by eliben** [comment]
Is this also the case when the user program is directly using registers rather than expecting PeachPy to allocate them? I mean code that works with registers manually rather than calling `GeneralPurposeRegister*`. Is this scenario supported at all?

**Comment by Maratyszcza** [comment]
Specifying registers explicitly is supported (and you can even combine explicit registers and virtual registers), but PeachPy will do stack management anyway.

**Comment by eliben** [comment]
So for example in this basic code:

```
with peachpy.x86_64.Function("Add", (x, y), peachpy.int32_t) as asm_function:
    reg_x = peachpy.x86_64.eax
    reg_y = peachpy.x86_64.ebx

    peachpy.x86_64.LOAD.ARGUMENT(reg_x, x)
    peachpy.x86_64.LOAD.ARGUMENT(reg_y, y)

    peachpy.x86_64.ADD(reg_x, reg_y)

    peachpy.x86_64.RETURN(reg_x)
```

PeachPy will save/restore `ebx` since it's callee saved. That's clear. But this doesn't prevent me mucking with the stack in between the first line of the context block and the `RETURN`, right? As long as I make sure to keep it in the same place.

This is useful when creating data on stack for function-internal use; for example, if you want to invoke the `WRITE` syscall it expects the address of a memory buffer, and the stack can be used for that.

Perhaps PeachPy local variables are better for this? I just couldn't find any example for how to use them.

**Comment by Maratyszcza** [comment]
There are several cases where manipulating `rsp` may cause problems:
- `LOAD.ARGUMENT` can be called in the middle of the function, and with some combinations of system ABI and function arguments it may need to load the argument from stack. Unless the stack frame needs realignment, PeachPy addresses on-stack arguments through `rsp` (otherwise it would setup `rbp` as stack frame base pointer). If a program changes `rsp` before using `LOAD.ARGUMENT`, PeachPy will miscalculate address for the argument.
- On-stack variables (see `LocalVariable` class) are always accessed through `rsp`. If you modify `rsp`, their address would be miscalculated.

Probably `LocalVariable` can help your use-case? You can use it to allocate fix-sized buffers, e.g.
```
buffer = LocalVariable(size=1024, alignment=4)
LEA(rcx, buffer)
```
The LocalVariable class is implemented in `peachpy.x86_64.function`

**Comment by eliben** [comment]
Thanks, this works - but it hits a bug with `LocalVariable`, I think. The function's `_layout_local_variables` does:

```
            for local_variable in local_variables_list:
                local_variable_address = roundup(local_variable_address, local_variable.alignment)
                local_variable.address = local_variable_address
                local_variable_address += local_variable.size
```

However, note that `address` in `LocalVariable` is a read-only property, so this raises an exception. As a workaround I tried adding a setter too, and it worked. However, it's not clear what the setter should do for subvariables.

**Comment by Maratyszcza** [comment]
Right, should be `local_variable._address`. Only top-level variables are in `local_variables_list`, and their subvariables would compute their own address via `offset` w.r.t. parent LocalVariables.

**Comment by eliben** [comment]
Sent a PR with a fix. LMK if you'd prefer to assign `_address` instead. It just seems weird to me to have an `address` as a property and then assign `_address` behind the scenes, but it's up to you.

**Comment by Maratyszcza** [comment]
Thank you. However, I would prefer to assign `_address`: `address` is a public property, and it should be read-only for code outside of PeachPy.

**Comment by eliben** [comment]
No problem - I can update the PR

**Comment by Maratyszcza** [comment]
Great! Once done, I'm ready to merge

**Comment by eliben** [comment]
Done! PTAL at #72.
