### ISSUE TITLE
Allow adding build tags to generated Go assembly files

### ISSUE THREAD

**Issue by dgryski** [Maratyszcza/PeachPy#75]
Build tags allow toggling (for example) between a pure Go implementation of a routine and the optimized assembly one.

At the moment I have to add these by hand to the generated assembly and I frequently forget. It would be nice if I could put directives in the peachpy file and have it add the appropriate comments.

**Comment by dgryski** [comment]
https://golang.org/pkg/go/build/#hdr-Build_Constraints

**Comment by Maratyszcza** [comment]
I think if you name the file `<anything>_amd64.s`, it will build only for x86-64. Do you need some other build restrictions?

**Comment by dgryski** [comment]
It's common to have a `noasm` tag that builds the Go version instead. This leads to duplicate symbol definitions if the assembly file is included because of the filename.

**Comment by Maratyszcza** [comment]
Ok, so what should I add to generate Golang assembly listings?

**Comment by Maratyszcza** [comment]
WIth f8e549a1daff077827aae1226bafe3422da9e134, I implemented generation of `// +build !noasm` tag like you use in [dgryski/go-groupvarint](https://github.com/dgryski/go-groupvarint/blob/master/nlz_amd64.s). Let me know if something else is needed.
