### ISSUE TITLE
WindowsError: [Error 32]  while creating objects from some python files of nnpack.

### ISSUE THREAD

**Issue by tsyj0404** [Maratyszcza/PeachPy#79]
Dear developer, @Maratyszcza 
Thank you for your contribution in this wonderful program. 

I tried to create objects in windows, but I encounter some problems when I tried to create some objects, such as  "o6x6k3x3.obj" and "2d-fourier-8x8.obj", but for other python source files, it worked well. (I think it is not a problem about system, windows or linux, because another developer have created these objects of nnpack in windows https://github.com/zeno40/nnpack , and the codes are not changed). But I encounter this problem.

I use this command: 
python -m peachpy.x86_64 -mabi=ms -mimage-format=ms-coff -mcpu=haswell -o o6x6k3x3.obj o6x6k3x3.py

I got this error while creating o6x6k3x3.obj:

Traceback (most recent call last):
  File "C:\Python27\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\lib\site-packages\peachpy-0.2.0-py2.7.egg\peachpy\x86_64\__main__.py", line 280, in <module>
    main()
  File "C:\Python27\lib\site-packages\peachpy-0.2.0-py2.7.egg\peachpy\x86_64\__main__.py", line 267, in main
    execute_script(writers, options.input[0])
  File "C:\Python27\lib\site-packages\peachpy-0.2.0-py2.7.egg\peachpy\x86_64\__main__.py", line 198, in execute_script
    execute_script(writers, source_filename)
  File "C:\Python27\lib\site-packages\peachpy-0.2.0-py2.7.egg\peachpy\writer.py", line 111, in __exit__
    os.unlink(self.output_file.name)
WindowsError: [Error 32] The process cannot access the file because it is being used by another process: 'o6x6k3x3.obj'

So what is the problem?  And if I try to build these objects in a different cpu, such as sandybridge, do I have to install peachpy in that system and create objects in that cpu? Or what I should do is just to change the command to "-mcpu=sandybridge" and create them in haswell cpu.

Thank you.

**Comment by Maratyszcza** [comment]
Some exception happened during compilation, the exception handling code tried to remove the output file (because it was only partially written), and this caused another, fatal, exception. You may try to apply #43 to get information about the original exception.
