### ISSUE TITLE
Requested for example with Unicorn interaction

### ISSUE THREAD

**Issue by GProtoZeroW** [Maratyszcza/PeachPy#82]
I am just starting out trying to learn assembly for a class, though I am a long time Python coder
I came across your library and also that of unicorn (http://www.unicorn-engine.org/docs/tutorial.html)
could you post a jupyter notebook example of generating the unicorn x86 example (and maybe more) using PeachPy and then how to generate the assembly code to the feed into unicorn emulator for arm64? 

Thank you

**Comment by Maratyszcza** [comment]
I believe it is possible to use PeachPy with Unicorn, but it is outside of my focus to work on an example. If you do figure out one, I welcome your pull request!
As for ARM64, the current version of PeachPy supports only x86-64.
