### ISSUE TITLE
Direct conversion to ASM?

### ISSUE THREAD

**Issue by vikramdurai** [Maratyszcza/PeachPy#83]
I'm sorry, I haven't even installed this, but I was looking at the README, and there is a *specific* syntax for PeachPy programs. Why isn't it that PeachPy exposes an **API** that you can use to compile programs with? Python programs that are written with the current PeachPy aren't *really* Python programs. With the current arrangement, PeachPy is actually a new language, with the syntax from Python. 

The solution would be to remove the extra syntax, and introduce a new function in its place, called `peachpy.asm()`. It would compile code **directly to ASM**. That way, most of the code is still portable, and only the **hotspots** are in assembler. Example:

```
import peachpy

def time_consuming_routine():
       # do something really hard

# lots of code
...

peachpy.asm(time_consuming_routine)
```

Also, what happens when a PeachPy program imports something like NumPy? Does PeachPy turn the whole module to ASM?

**Comment by Maratyszcza** [comment]
The use-case you are asking is supported, here's an example (from README):

from peachpy import *
from peachpy.x86_64 import *

```
x = Argument(int32_t)
y = Argument(int32_t)

with Function("Add", (x, y), int32_t) as asm_function:
    reg_x = GeneralPurposeRegister32()
    reg_y = GeneralPurposeRegister32()

    LOAD.ARGUMENT(reg_x, x)
    LOAD.ARGUMENT(reg_y, y)

    ADD(reg_x, reg_y)

    RETURN(reg_x)

python_function = asm_function.finalize(abi.detect()).encode().load()

print(python_function(2, 2)) # -> prints "4"
```
