### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by zeno40** [Maratyszcza/PeachPy#86]
In the CMakeLists.txt (line:326-328) of NNPACK you specify 
${PYTHON_EXECUTABLE} -m peachpy.x86_64 -mabi=sysv -g4 -mimage-format=${PEACHPY_IMAGE_FORMAT}

I'm wondering what is the meaning of the -g4 parameter

thanks

**Comment by Maratyszcza** [comment]
`-g*n*` parameter with `*n* > 0` makes PeachPy record which line of Python code produced each assembly instruction. Currently, this information is only used for error reporting.
